---
output:
  pdf_document: default
  html_document: default
---



```{r}
mysoln <- list(student = c("Huanyu Liu", "Jiaqi Li", "Hyeuk Jung", "Xichen Luo"))
```


## Question 1

1. You can invest $10,000 in a certificate of deposit (CD) offered by your bank. The CD is for 3 years and the bank quotes you a rate of 6%. How much will you have in 3 years if the 6% is

(a) an EAR?

$\$ 10,000 \times (1+0.06)^{3} = \$11,910$

(b) a quarterly APR?

$\$ 10,000 \times (1 + \frac{0.06}{4})^{3 \times 4} = \$ 11,956$

(c) a monthly APR?

$\$ 10,000 \times (1+\frac{0.06}{12})^{3 \times 12} = \$11,967$


## Question 2
2. Charlotte is negotiating a prenuptial agreement with Bunny. Under the agreement, Charlotte will be receiving 10% of $500K every three years (with the first payment occurring three years after the wedding). Bunny claims that under the agreement, and provided that the marriage lasts for 30 years, Charlotte is worth $500K.

(a) Charlotte has some doubts, and talks it over with Miranda, who has studied some finance during her law school education. Miranda claims that under the agreement, Charlotte is worth significantly less than $500K. Why is Miranda right, and what is her argument? How much is the agreement worth provided that Charlotte's annual discount rate is 5%?

payment = $\$500,000 \times 0.1$, discount rate = $5\%\\$
          As the payment is made every three years, discount rate for 3 years is:$\\$ $(1+1.05)^{3}-1 = 0.1576\\$
Therefore, the present value of payment for next 30 years,$\\$
$PV = \frac{50,000}{(1+0.1576)} + \frac{50,000}{(1+0.1576)^{2}} + ... + \frac{50,000}{(1+0.1576)^{10}} = \$ 243,814\\$



(b) Miranda advises Charlotte to negotiate an agreement under which she is worth $700K. What should each of the 10 (equal) payments be, provided that Charlotte’s annual discount rate is 5%?

$700,000 = \frac{CF}{(1+0.1576)} + \frac{CF}{(1+0.1576)^{2}} + ... + \frac{CF}{(1+0.1576)^{10}}\\$
$CF = \frac{700,000 \times 0.1576}{1 - (\frac{1}{1.1576})^{10}} = \$143,552\\$


## Question 3
3. You are trying to determine your standard of living after retirement. You make the following assumptions. First, you will earn $200,000 for each of the next 35 years, and
save 30% of that amount. Second, payments are annual and the first payment is one year from today. Third, interest rates will be 4% per year forever.

(a) Compute how much money you will have saved at the end of the 35th year.

$n=year=35\\$
$r=0.04\\$
$save=200,000\times0.3\\$
$sumFv = \sum_{i=1}^{n} save\times(1+r)^{i}\\$
$sumFv=4,419,133$

(b) What is the amount you can consume during each of your retirement years? Assume that there are 20 retirement years, and that consumption takes place at the end of each year. (Note: If you have not computed the answer to part (a), denote this answer by X and do part (b).)

$n=retirementYear=20\\$
$sumFv = \sum_{j=1}^{n} \frac{consumption}{(1+r)^{j}}\\$
$consumption = 325,168\\$

## Question 4
4. You are considering buying a two-bedroom apartment for $600,000. You plan to make a $200,000 down payment and take a $400,000 30-year mortgage for the rest. The interest rate on the mortgage is 7% monthly APR.
(a) What is the effective annual rate?


$r=0.07\\$
$\text{effective annual rate} = (1+\frac{r}{12})^{12}-1\\$
The effective annual rate is 7.229%.$\\$

(b) What is the monthly payment?
$pvMortgage = 400,000\\$
$n=30\times12\\$
$monthlyR=r\div12\\$
$pvMortgage = \sum_{i=1}^{n} \frac{payment}{(1+monthly-r)^{i}}\\$
$pvMortgage = 2,661.21\\$

(c) How much do you owe the bank immediately after the twentieth monthly pay- ment?
Hint: There is a very quick and a very slow way to answer part (c).

Quick way

$n = 30\times12-20\\$
$cf=payment\\$
$pv_{20} = \sum_{j=1}^{n} \frac{payment}{(1+monthly-r)^{j}}\\$
$pv_{20} = 393,066.03\\$


## Question 5
5. Give an example of a project with no IRR and an example with multiple IRRs.

No IRR:$\\$
$PV=200+\frac{600}{1+r}+\frac{500}{(1+r)^2}\\$
IRR is the point when PV=0. Suppose CF0=200, CF1>0, and CF2>0, r does not exist, which can make PV=0 $\\$

Multiple IRR:$\\$
Suppose the cash flows are as following, $\\$
$0=-100+\frac{600}{1+IRR}-\frac{800}{(1+IRR)^2}$,We will get $IRR1=1$, and $IRR2=3$



